language: java
sudo: false
jdk:
  - openjdk7

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
# fetch 3rd party apis and such
- git submodule update --init
- cd sub/Growthcraft && git submodule update --init
- chmod +x ./gradlew

install: ./gradlew setupCIWorkspace -S

script: |
  ./gradlew build &&
  ls -la build/libs

# Deploy the artifacts back to GitHub
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH
  file_glob: true
  file:
    - "build/libs/netherloid-*-release.jar"
    - "build/libs/netherloid-*-api.jar"
    - "build/libs/netherloid-*-dev.jar"
    - "build/libs/netherloid-*-javadoc.jar"
    - "build/libs/netherloid-*-sources.jar"
  skip_cleanup: true
  on:
    tags: true
